apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: mysql
  name: mysql-config
  namespace: production
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS simple_api_db;
    USE simple_api_db;
    CREATE TABLE IF NOT EXISTS users (
        id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
        name VARCHAR(100) NOT NULL,
        email VARCHAR(100) NOT NULL,
        password VARCHAR(100) NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
