apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: prometheus
  name: prometheus-config
  namespace: production
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['35.232.29.168:8000']
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter:9100']