apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
  namespace: production
spec:
  selector:
    app: backend
  ports:
    - name: "backend-service"
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
