apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: production
spec:
  selector:
    app: frontend
  ports:
    - name: "frontend-service"
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
