apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: production
spec:
  selector:
    app: grafana
  ports:
    - name: "grafana-service"
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
