apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: mysql
  namespace: production
spec:
  selector:
    app: db
  ports:
    - name: "mysql"
      port: 3306
      targetPort: 3306
      protocol: TCP
  type: ClusterIP