apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-exporter
  name: node-exporter
  namespace: production
spec:
  selector:
    app: node-exporter
  ports:
    - name: "node-exporter-service"
      protocol: TCP
      port: 9100
      targetPort: 9100
  type: ClusterIP